from typing import Dict, List

from common.action_space.actions import Action, MacroAction
from common.action_space.primitives import *

STD_ACTION_SPACE: List[Action] = [
    REWRITE,
    REWRITE_Z,
    REFACTOR,
    REFACTOR_Z,
    RESUB,
    RESUB_Z,
    BALANCE,
]

EXTENDED_ACTION_SPACE: List[Action] = [
    *STD_ACTION_SPACE,
    FRAIG,
    SOPB,
    BLUT,
    DSDB,
]

STRASH_EXTENDED_ACTION_SPACE: List[Action] = [
    *EXTENDED_ACTION_SPACE,
    STRASH,
]

ACTION_SPACES: Dict[str, List[Action]] = {
    "standard": STD_ACTION_SPACE,
    "extended": EXTENDED_ACTION_SPACE,
    "strash_extended": STRASH_EXTENDED_ACTION_SPACE,
}

EXTENDED_MACRO_SPACE_TEST: List[MacroAction] = [
    MacroAction(11, "&get -n; &dsdb; &put; fraig; resub; &get -n; &sopb; &put; "),
    MacroAction(12, "fraig; resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; "),
    MacroAction(13, "resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; "),
    MacroAction(14, "&get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; fraig; "),
    MacroAction(120, "balance; rewrite -z; &get -n; &sopb; &put; &get -n; &sopb; &put; "),
    MacroAction(121, "rewrite -z; &get -n; &sopb; &put; &get -n; &sopb; &put; fraig; "),
    MacroAction(122, "&get -n; &sopb; &put; &get -n; &sopb; &put; fraig; &get -n; &blut; &put; "),
    MacroAction(283, "balance; fraig; &get -n; &sopb; &put; &get -n; &sopb; &put; "),
    MacroAction(284, "fraig; &get -n; &sopb; &put; &get -n; &sopb; &put; refactor -z; "),
    MacroAction(285, "&get -n; &sopb; &put; &get -n; &sopb; &put; refactor -z; refactor -z; "),

    MacroAction(47, "refactor; rewrite -z; balance; resub -z; "),
    MacroAction(48, "rewrite -z; balance; resub -z; refactor -z; "),
    MacroAction(49, "balance; resub -z; refactor -z; refactor; "),
    MacroAction(57, "resub; refactor -z; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(58, "refactor -z; &get -n; &dsdb; &put; refactor -z; refactor; "),
    MacroAction(59, "&get -n; &dsdb; &put; refactor -z; refactor; resub -z; "),
    MacroAction(84,  "balance; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(85,  "&get -n; &blut; &put; refactor; resub -z; rewrite; "),
    MacroAction(218, "rewrite; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(219, "&get -n; &blut; &put; refactor; resub -z; resub -z; "),

    MacroAction(43, "refactor -z; &get -n; &dsdb; &put; resub -z; &get -n; &blut; &put; "),
    MacroAction(44, "&get -n; &dsdb; &put; resub -z; &get -n; &blut; &put; refactor; "),
    MacroAction(118, "refactor -z; resub; balance; &get -n; &dsdb; &put; "),
    MacroAction(119, "resub; balance; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(145, "resub -z; resub; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(146, "resub; refactor -z; &get -n; &dsdb; &put; &get -n; &blut; &put; "),
    MacroAction(147, "refactor -z; &get -n; &dsdb; &put; &get -n; &blut; &put; refactor -z; "),

    MacroAction(0, ""),
    MacroAction(999, "balance; balance; balance; balance; "),

    MacroAction(777, "&get -n; &blut; &put; &get -n; &sopb; &put; &get -n; &dsdb; &put; &get -n; &blut; &put;"),
    MacroAction(666, "rewrite; rewrite; rewrite; rewrite; "),
]

EXTENDED_MACRO_SPACE_ALL: List[MacroAction] = [
    # Multi RS Adder
    MacroAction(1,  "&get -n; &sopb; &put; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(2,  "&get -n; &blut; &put; refactor; resub -z; &get -n; &blut; &put; "),
    MacroAction(3,  "refactor; resub -z; &get -n; &blut; &put; &get -n; &blut; &put; "),
    MacroAction(4,  "resub -z; &get -n; &blut; &put; &get -n; &blut; &put; balance; "),
    MacroAction(5,  "&get -n; &blut; &put; &get -n; &blut; &put; balance; &get -n; &dsdb; &put; "),
    MacroAction(6,  "&get -n; &blut; &put; balance; &get -n; &dsdb; &put; refactor; "),
    MacroAction(7,  "balance; &get -n; &dsdb; &put; refactor; balance; "),
    MacroAction(8,  "&get -n; &dsdb; &put; refactor; balance; &get -n; &dsdb; &put; "),
    MacroAction(9,  "refactor; balance; &get -n; &dsdb; &put; fraig; "),
    MacroAction(10, "balance; &get -n; &dsdb; &put; fraig; resub; "),
    MacroAction(11, "&get -n; &dsdb; &put; fraig; resub; &get -n; &sopb; &put; "),
    MacroAction(12, "fraig; resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; "),
    MacroAction(13, "resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; "),
    MacroAction(14, "&get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; fraig; "),
    MacroAction(15, "&get -n; &dsdb; &put; rewrite -z; fraig; balance; "),
    MacroAction(16, "rewrite -z; fraig; balance; resub; "),
    MacroAction(17, "fraig; balance; resub; rewrite; "),

    # Multi RS Div
    MacroAction(18, "&get -n; &dsdb; &put; rewrite; &get -n; &dsdb; &put; refactor; "),
    MacroAction(19, "rewrite; &get -n; &dsdb; &put; refactor; &get -n; &sopb; &put; "),
    MacroAction(20, "&get -n; &dsdb; &put; refactor; &get -n; &sopb; &put; resub; "),
    MacroAction(21, "refactor; &get -n; &sopb; &put; resub; rewrite; "),
    MacroAction(22, "&get -n; &sopb; &put; resub; rewrite; resub -z; "),
    MacroAction(23, "resub; rewrite; resub -z; &get -n; &blut; &put; "),
    MacroAction(24, "rewrite; resub -z; &get -n; &blut; &put; refactor -z; "),
    MacroAction(25, "resub -z; &get -n; &blut; &put; refactor -z; resub -z; "),
    MacroAction(26, "&get -n; &blut; &put; refactor -z; resub -z; rewrite; "),
    MacroAction(27, "refactor -z; resub -z; rewrite; resub -z; "),
    MacroAction(28, "resub -z; rewrite; resub -z; balance; "),
    MacroAction(29, "rewrite; resub -z; balance; resub -z; "),
    MacroAction(30, "resub -z; balance; resub -z; fraig; "),
    MacroAction(31, "balance; resub -z; fraig; &get -n; &blut; &put; "),
    MacroAction(32, "resub -z; fraig; &get -n; &blut; &put; &get -n; &dsdb; &put; "),
    MacroAction(33, "fraig; &get -n; &blut; &put; &get -n; &dsdb; &put; rewrite; "),
    MacroAction(34, "&get -n; &blut; &put; &get -n; &dsdb; &put; rewrite; balance; "),

    # Multi RS Log2
    MacroAction(35, "refactor -z; &get -n; &blut; &put; fraig; resub -z; "),
    MacroAction(36, "&get -n; &blut; &put; fraig; resub -z; rewrite -z; "),
    MacroAction(37, "fraig; resub -z; rewrite -z; &get -n; &blut; &put; "),
    MacroAction(38, "resub -z; rewrite -z; &get -n; &blut; &put; &get -n; &sopb; &put; "),
    MacroAction(39, "rewrite -z; &get -n; &blut; &put; &get -n; &sopb; &put; refactor -z; "),
    MacroAction(40, "&get -n; &blut; &put; &get -n; &sopb; &put; refactor -z; refactor -z; "),
    MacroAction(41, "&get -n; &sopb; &put; refactor -z; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(42, "refactor -z; refactor -z; &get -n; &dsdb; &put; resub -z; "),
    MacroAction(43, "refactor -z; &get -n; &dsdb; &put; resub -z; &get -n; &blut; &put; "),
    MacroAction(44, "&get -n; &dsdb; &put; resub -z; &get -n; &blut; &put; refactor; "),
    MacroAction(45, "resub -z; &get -n; &blut; &put; refactor; rewrite -z; "),
    MacroAction(46, "&get -n; &blut; &put; refactor; rewrite -z; balance; "),
    MacroAction(47, "refactor; rewrite -z; balance; resub -z; "),
    MacroAction(48, "rewrite -z; balance; resub -z; refactor -z; "),
    MacroAction(49, "balance; resub -z; refactor -z; refactor; "),
    MacroAction(50, "resub -z; refactor -z; refactor; &get -n; &blut; &put; "),
    MacroAction(51, "refactor -z; refactor; &get -n; &blut; &put; balance; "),

    # Multi RS Max 
    MacroAction(52, "refactor -z; refactor -z; balance; resub -z; "),
    MacroAction(53, "refactor -z; balance; resub -z; rewrite; "),
    MacroAction(54, "balance; resub -z; rewrite; resub; "),
    MacroAction(55, "resub -z; rewrite; resub; refactor -z; "),
    MacroAction(56, "rewrite; resub; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(57, "resub; refactor -z; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(58, "refactor -z; &get -n; &dsdb; &put; refactor -z; refactor; "),
    MacroAction(59, "&get -n; &dsdb; &put; refactor -z; refactor; resub -z; "),
    MacroAction(60, "refactor -z; refactor; resub -z; balance; "),
    MacroAction(61, "refactor; resub -z; balance; &get -n; &dsdb; &put; "),
    MacroAction(62, "resub -z; balance; &get -n; &dsdb; &put; resub; "),
    MacroAction(63, "balance; &get -n; &dsdb; &put; resub; refactor; "),
    MacroAction(64, "&get -n; &dsdb; &put; resub; refactor; resub -z; "),
    MacroAction(65, "resub; refactor; resub -z; &get -n; &blut; &put; "),
    MacroAction(66, "refactor; resub -z; &get -n; &blut; &put; &get -n; &sopb; &put; "),
    MacroAction(67, "resub -z; &get -n; &blut; &put; &get -n; &sopb; &put; rewrite; "),
    MacroAction(68, "&get -n; &blut; &put; &get -n; &sopb; &put; rewrite; balance; "),

    # Multi RS Multiplier
    MacroAction(69,  "resub -z; fraig; &get -n; &sopb; &put; rewrite; "),
    MacroAction(70,  "fraig; &get -n; &sopb; &put; rewrite; refactor -z; "),
    MacroAction(71,  "&get -n; &sopb; &put; rewrite; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(72,  "rewrite; refactor -z; &get -n; &dsdb; &put; resub -z; "),
    MacroAction(73,  "refactor -z; &get -n; &dsdb; &put; resub -z; resub -z; "),
    MacroAction(74,  "&get -n; &dsdb; &put; resub -z; resub -z; &get -n; &sopb; &put; "),
    MacroAction(75,  "resub -z; resub -z; &get -n; &sopb; &put; refactor; "),
    MacroAction(76,  "resub -z; &get -n; &sopb; &put; refactor; rewrite; "),
    MacroAction(77,  "&get -n; &sopb; &put; refactor; rewrite; &get -n; &dsdb; &put; "),
    MacroAction(78,  "refactor; rewrite; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(79,  "rewrite; &get -n; &dsdb; &put; &get -n; &dsdb; &put; balance; "),
    MacroAction(80,  "&get -n; &dsdb; &put; &get -n; &dsdb; &put; balance; resub -z; "),
    MacroAction(81,  "&get -n; &dsdb; &put; balance; resub -z; balance; "),
    MacroAction(82,  "balance; resub -z; balance; &get -n; &blut; &put; "),
    MacroAction(83,  "resub -z; balance; &get -n; &blut; &put; refactor; "),
    MacroAction(84,  "balance; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(85,  "&get -n; &blut; &put; refactor; resub -z; rewrite; "),

    # Multi RS Sin
    MacroAction(86,  "rewrite; &get -n; &dsdb; &put; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(87,  "&get -n; &dsdb; &put; refactor -z; &get -n; &dsdb; &put; balance; "),
    MacroAction(88,  "refactor -z; &get -n; &dsdb; &put; balance; refactor; "),
    MacroAction(89,  "&get -n; &dsdb; &put; balance; refactor; rewrite; "),
    MacroAction(90,  "balance; refactor; rewrite; &get -n; &dsdb; &put; "),
    MacroAction(91,  "refactor; rewrite; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(92,  "rewrite; &get -n; &dsdb; &put; refactor -z; &get -n; &blut; &put; "),
    MacroAction(93,  "&get -n; &dsdb; &put; refactor -z; &get -n; &blut; &put; resub -z; "),
    MacroAction(94,  "refactor -z; &get -n; &blut; &put; resub -z; fraig; "),
    MacroAction(95,  "&get -n; &blut; &put; resub -z; fraig; refactor; "),
    MacroAction(96,  "resub -z; fraig; refactor; &get -n; &dsdb; &put; "),
    MacroAction(97,  "fraig; refactor; &get -n; &dsdb; &put; resub; "),
    MacroAction(98,  "refactor; &get -n; &dsdb; &put; resub; resub -z; "),
    MacroAction(99,  "&get -n; &dsdb; &put; resub; resub -z; resub; "),
    MacroAction(100, "resub; resub -z; resub; resub; "),
    MacroAction(101, "resub -z; resub; resub; rewrite; "),
    MacroAction(102, "resub; resub; rewrite; resub -z; "),

    # Multi RS Square Root
    MacroAction(103, "&get -n; &dsdb; &put; resub -z; &get -n; &blut; &put; &get -n; &blut; &put; "),
    MacroAction(104, "resub -z; &get -n; &blut; &put; &get -n; &blut; &put; &get -n; &dsdb; &put; "),
    MacroAction(105, "&get -n; &blut; &put; &get -n; &blut; &put; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(106, "&get -n; &blut; &put; &get -n; &dsdb; &put; &get -n; &dsdb; &put; resub; "),
    MacroAction(107, "&get -n; &dsdb; &put; &get -n; &dsdb; &put; resub; &get -n; &dsdb; &put; "),
    MacroAction(108, "&get -n; &dsdb; &put; resub; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(109, "resub; &get -n; &dsdb; &put; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(110, "&get -n; &dsdb; &put; refactor -z; &get -n; &dsdb; &put; fraig; "),
    MacroAction(111, "refactor -z; &get -n; &dsdb; &put; fraig; resub -z; "),
    MacroAction(112, "&get -n; &dsdb; &put; fraig; resub -z; refactor -z; "),
    MacroAction(113, "fraig; resub -z; refactor -z; balance; "),
    MacroAction(114, "resub -z; refactor -z; balance; refactor -z; "),
    MacroAction(115, "refactor -z; balance; refactor -z; refactor -z; "),
    MacroAction(116, "balance; refactor -z; refactor -z; resub; "),
    MacroAction(117, "refactor -z; refactor -z; resub; balance; "),
    MacroAction(118, "refactor -z; resub; balance; &get -n; &dsdb; &put; "),
    MacroAction(119, "resub; balance; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),

    # Multi RS Square
    MacroAction(120, "balance; rewrite -z; &get -n; &sopb; &put; &get -n; &sopb; &put; "),
    MacroAction(121, "rewrite -z; &get -n; &sopb; &put; &get -n; &sopb; &put; fraig; "),
    MacroAction(122, "&get -n; &sopb; &put; &get -n; &sopb; &put; fraig; &get -n; &blut; &put; "),
    MacroAction(123, "&get -n; &sopb; &put; fraig; &get -n; &blut; &put; resub; "),
    MacroAction(124, "fraig; &get -n; &blut; &put; resub; fraig; "),
    MacroAction(125, "&get -n; &blut; &put; resub; fraig; refactor -z; "),
    MacroAction(126, "resub; fraig; refactor -z; refactor; "),
    MacroAction(127, "fraig; refactor -z; refactor; resub -z; "),
    MacroAction(128, "refactor -z; refactor; resub -z; resub -z; "),
    MacroAction(129, "refactor; resub -z; resub -z; refactor; "),
    MacroAction(130, "resub -z; resub -z; refactor; &get -n; &dsdb; &put; "),
    MacroAction(131, "resub -z; refactor; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(132, "refactor; &get -n; &dsdb; &put; refactor -z; refactor; "),
    MacroAction(133, "&get -n; &dsdb; &put; refactor -z; refactor; refactor; "),
    MacroAction(134, "refactor -z; refactor; refactor; resub -z; "),
    MacroAction(135, "refactor; refactor; resub -z; &get -n; &blut; &put; "),
    MacroAction(136, "refactor; resub -z; &get -n; &blut; &put; &get -n; &dsdb; &put; "),

    # BO Adder
    MacroAction(137, "rewrite; &get -n; &blut; &put; refactor; &get -n; &blut; &put; "),
    MacroAction(138, "&get -n; &blut; &put; refactor; &get -n; &blut; &put; &get -n; &sopb; &put; "),
    MacroAction(139, "refactor; &get -n; &blut; &put; &get -n; &sopb; &put; &get -n; &blut; &put; "),
    MacroAction(140, "&get -n; &blut; &put; &get -n; &sopb; &put; &get -n; &blut; &put; resub -z; "),
    MacroAction(141, "&get -n; &sopb; &put; &get -n; &blut; &put; resub -z; balance; "),
    MacroAction(142, "&get -n; &blut; &put; resub -z; balance; resub -z; "),
    MacroAction(143, "resub -z; balance; resub -z; resub; "),
    MacroAction(144, "balance; resub -z; resub; refactor -z; "),
    MacroAction(145, "resub -z; resub; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(146, "resub; refactor -z; &get -n; &dsdb; &put; &get -n; &blut; &put; "),
    MacroAction(147, "refactor -z; &get -n; &dsdb; &put; &get -n; &blut; &put; refactor -z; "),
    MacroAction(148, "&get -n; &dsdb; &put; &get -n; &blut; &put; refactor -z; refactor -z; "),
    MacroAction(149, "&get -n; &blut; &put; refactor -z; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(150, "refactor -z; refactor -z; &get -n; &dsdb; &put; rewrite; "),
    MacroAction(151, "refactor -z; &get -n; &dsdb; &put; rewrite; rewrite -z; "),
    MacroAction(152, "&get -n; &dsdb; &put; rewrite; rewrite -z; resub -z; "),
    MacroAction(153, "rewrite; rewrite -z; resub -z; resub; "),
    
    # BO Div
    MacroAction(154, "balance; rewrite -z; resub -z; resub; "),
    MacroAction(155, "rewrite -z; resub -z; resub; resub -z; "),
    MacroAction(156, "resub -z; resub; resub -z; refactor; "),
    MacroAction(157, "resub; resub -z; refactor; balance; "),
    MacroAction(158, "resub -z; refactor; balance; &get -n; &dsdb; &put; "),
    MacroAction(159, "refactor; balance; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(160, "balance; &get -n; &dsdb; &put; refactor -z; &get -n; &sopb; &put; "),
    MacroAction(161, "&get -n; &dsdb; &put; refactor -z; &get -n; &sopb; &put; fraig; "),
    MacroAction(162, "refactor -z; &get -n; &sopb; &put; fraig; resub; "),
    MacroAction(163, "&get -n; &sopb; &put; fraig; resub; rewrite; "),
    MacroAction(164, "fraig; resub; rewrite; &get -n; &dsdb; &put; "),
    MacroAction(165, "resub; rewrite; &get -n; &dsdb; &put; refactor; "),
    MacroAction(166, "rewrite; &get -n; &dsdb; &put; refactor; &get -n; &blut; &put; "),
    MacroAction(167, "&get -n; &dsdb; &put; refactor; &get -n; &blut; &put; resub; "),
    MacroAction(168, "refactor; &get -n; &blut; &put; resub; fraig; "),
    MacroAction(169, "&get -n; &blut; &put; resub; fraig; refactor; "),
    MacroAction(170, "resub; fraig; refactor; rewrite; "),

    # BO Hyp
    MacroAction(171, "fraig; fraig; &get -n; &blut; &put; resub; "),
    MacroAction(172, "fraig; &get -n; &blut; &put; resub; rewrite; "),
    MacroAction(173, "&get -n; &blut; &put; resub; rewrite; rewrite; "),
    MacroAction(174, "resub; rewrite; rewrite; &get -n; &dsdb; &put; "),
    MacroAction(175, "rewrite; rewrite; &get -n; &dsdb; &put; refactor; "),
    MacroAction(176, "rewrite; &get -n; &dsdb; &put; refactor; refactor; "),
    MacroAction(177, "&get -n; &dsdb; &put; refactor; refactor; balance; "),
    MacroAction(178, "refactor; refactor; balance; balance; "),
    MacroAction(179, "refactor; balance; balance; refactor; "),
    MacroAction(180, "balance; balance; refactor; resub -z; "),
    MacroAction(181, "balance; refactor; resub -z; &get -n; &dsdb; &put; "),
    MacroAction(182, "refactor; resub -z; &get -n; &dsdb; &put; &get -n; &blut; &put; "),
    MacroAction(183, "resub -z; &get -n; &dsdb; &put; &get -n; &blut; &put; &get -n; &dsdb; &put; "),
    MacroAction(184, "&get -n; &dsdb; &put; &get -n; &blut; &put; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(185, "&get -n; &blut; &put; &get -n; &dsdb; &put; &get -n; &dsdb; &put; rewrite; "),
    MacroAction(186, "&get -n; &dsdb; &put; &get -n; &dsdb; &put; rewrite; &get -n; &sopb; &put; "),
    MacroAction(187, "&get -n; &dsdb; &put; rewrite; &get -n; &sopb; &put; refactor -z; "),

    # BO Log2
    MacroAction(188, "balance; &get -n; &sopb; &put; &get -n; &dsdb; &put; fraig; "),
    MacroAction(189, "&get -n; &sopb; &put; &get -n; &dsdb; &put; fraig; &get -n; &dsdb; &put; "),
    MacroAction(190, "&get -n; &dsdb; &put; fraig; &get -n; &dsdb; &put; fraig; "),
    MacroAction(191, "fraig; &get -n; &dsdb; &put; fraig; resub; "),
    MacroAction(192, "&get -n; &dsdb; &put; fraig; resub; &get -n; &dsdb; &put; "),
    MacroAction(193, "fraig; resub; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(194, "resub; &get -n; &dsdb; &put; &get -n; &dsdb; &put; resub; "),
    MacroAction(195, "&get -n; &dsdb; &put; &get -n; &dsdb; &put; resub; rewrite; "),
    MacroAction(196, "&get -n; &dsdb; &put; resub; rewrite; rewrite; "),
    MacroAction(197, "resub; rewrite; rewrite; &get -n; &dsdb; &put; "),
    MacroAction(198, "rewrite; rewrite; &get -n; &dsdb; &put; &get -n; &dsdb; &put; "),
    MacroAction(199, "rewrite; &get -n; &dsdb; &put; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(200, "&get -n; &dsdb; &put; &get -n; &dsdb; &put; refactor -z; refactor; "),
    MacroAction(201, "&get -n; &dsdb; &put; refactor -z; refactor; rewrite; "),
    MacroAction(202, "refactor -z; refactor; rewrite; refactor; "),
    MacroAction(203, "refactor; rewrite; refactor; refactor -z; "),
    MacroAction(204, "rewrite; refactor; refactor -z; &get -n; &blut; &put; "),

    # BO Max
    MacroAction(205, "&get -n; &dsdb; &put; &get -n; &sopb; &put; fraig; &get -n; &blut; &put; "),
    MacroAction(206, "&get -n; &sopb; &put; fraig; &get -n; &blut; &put; fraig; "),
    MacroAction(207, "fraig; &get -n; &blut; &put; fraig; resub; "),
    MacroAction(208, "&get -n; &blut; &put; fraig; resub; rewrite; "),
    MacroAction(209, "fraig; resub; rewrite; &get -n; &blut; &put; "),
    MacroAction(210, "resub; rewrite; &get -n; &blut; &put; refactor; "),
    MacroAction(211, "rewrite; &get -n; &blut; &put; refactor; rewrite -z; "),
    MacroAction(212, "&get -n; &blut; &put; refactor; rewrite -z; refactor -z; "),
    MacroAction(213, "refactor; rewrite -z; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(214, "rewrite -z; refactor -z; &get -n; &dsdb; &put; fraig; "),
    MacroAction(215, "refactor -z; &get -n; &dsdb; &put; fraig; rewrite; "),
    MacroAction(216, "&get -n; &dsdb; &put; fraig; rewrite; &get -n; &blut; &put; "),
    MacroAction(217, "fraig; rewrite; &get -n; &blut; &put; refactor; "),
    MacroAction(218, "rewrite; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(219, "&get -n; &blut; &put; refactor; resub -z; resub -z; "),
    MacroAction(220, "refactor; resub -z; resub -z; &get -n; &blut; &put; "),
    MacroAction(221, "resub -z; resub -z; &get -n; &blut; &put; refactor; "),

    # BO Multiplier
    MacroAction(222, "resub -z; &get -n; &blut; &put; &get -n; &sopb; &put; refactor; "),
    MacroAction(223, "&get -n; &blut; &put; &get -n; &sopb; &put; refactor; rewrite; "),
    MacroAction(224, "&get -n; &sopb; &put; refactor; rewrite; refactor -z; "),
    MacroAction(225, "refactor; rewrite; refactor -z; refactor; "),
    MacroAction(226, "rewrite; refactor -z; refactor; &get -n; &dsdb; &put; "),
    MacroAction(227, "refactor -z; refactor; &get -n; &dsdb; &put; balance; "),
    MacroAction(228, "refactor; &get -n; &dsdb; &put; balance; balance; "),
    MacroAction(229, "&get -n; &dsdb; &put; balance; balance; &get -n; &dsdb; &put; "),
    MacroAction(230, "balance; balance; &get -n; &dsdb; &put; resub; "),
    MacroAction(231, "balance; &get -n; &dsdb; &put; resub; refactor -z; "),
    MacroAction(232, "&get -n; &dsdb; &put; resub; refactor -z; resub; "),
    MacroAction(233, "resub; refactor -z; resub; &get -n; &sopb; &put; "),
    MacroAction(234, "refactor -z; resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; "),
    MacroAction(235, "resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite; "),
    MacroAction(236, "&get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite; refactor; "),
    MacroAction(237, "&get -n; &dsdb; &put; rewrite; refactor; resub -z; "),
    MacroAction(238, "rewrite; refactor; resub -z; resub -z; "),

    # BO Sin
    MacroAction(239, "&get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; fraig; "),
    MacroAction(240, "resub -z; &get -n; &dsdb; &put; fraig; &get -n; &dsdb; &put; "),
    MacroAction(241, "&get -n; &dsdb; &put; fraig; &get -n; &dsdb; &put; balance; "),
    MacroAction(242, "fraig; &get -n; &dsdb; &put; balance; rewrite; "),
    MacroAction(243, "&get -n; &dsdb; &put; balance; rewrite; rewrite; "),
    MacroAction(244, "balance; rewrite; rewrite; refactor -z; "),
    MacroAction(245, "rewrite; rewrite; refactor -z; refactor; "),
    MacroAction(246, "rewrite; refactor -z; refactor; refactor -z; "),
    MacroAction(247, "refactor -z; refactor; refactor -z; refactor -z; "),
    MacroAction(248, "refactor; refactor -z; refactor -z; resub; "),
    MacroAction(249, "refactor -z; refactor -z; resub; &get -n; &dsdb; &put; "),
    MacroAction(250, "refactor -z; resub; &get -n; &dsdb; &put; &get -n; &blut; &put; "),
    MacroAction(251, "resub; &get -n; &dsdb; &put; &get -n; &blut; &put; balance; "),
    MacroAction(252, "&get -n; &dsdb; &put; &get -n; &blut; &put; balance; balance; "),
    MacroAction(253, "&get -n; &blut; &put; balance; balance; resub -z; "),
    MacroAction(254, "balance; balance; resub -z; resub -z; "),
    MacroAction(255, "balance; resub -z; resub -z; &get -n; &dsdb; &put; "),

    # BO Square Root
    MacroAction(256, "&get -n; &blut; &put; resub; fraig; resub; "),
    MacroAction(257, "resub; fraig; resub; fraig; "),
    MacroAction(258, "fraig; resub; fraig; rewrite; "),
    MacroAction(259, "resub; fraig; rewrite; rewrite; "),
    MacroAction(260, "fraig; rewrite; rewrite; &get -n; &blut; &put; "),
    MacroAction(261, "rewrite; rewrite; &get -n; &blut; &put; fraig; "),
    MacroAction(262, "rewrite; &get -n; &blut; &put; fraig; fraig; "),
    MacroAction(263, "&get -n; &blut; &put; fraig; fraig; refactor -z; "),
    MacroAction(264, "fraig; fraig; refactor -z; refactor -z; "),
    MacroAction(265, "fraig; refactor -z; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(266, "refactor -z; refactor -z; &get -n; &dsdb; &put; resub -z; "),
    MacroAction(267, "refactor -z; &get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; "),
    MacroAction(268, "&get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; fraig; "),
    MacroAction(269, "resub -z; &get -n; &dsdb; &put; fraig; rewrite -z; "),
    MacroAction(270, "&get -n; &dsdb; &put; fraig; rewrite -z; rewrite; "),
    MacroAction(271, "fraig; rewrite -z; rewrite; &get -n; &blut; &put; "),
    MacroAction(272, "rewrite -z; rewrite; &get -n; &blut; &put; &get -n; &blut; &put; "),

    # BO Square
    MacroAction(273, "rewrite; refactor; rewrite; refactor; "),
    MacroAction(274, "refactor; rewrite; refactor; &get -n; &dsdb; &put; "),
    MacroAction(275, "rewrite; refactor; &get -n; &dsdb; &put; resub -z; "),
    MacroAction(276, "refactor; &get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; "),
    MacroAction(277, "&get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; refactor -z; "),
    MacroAction(278, "resub -z; &get -n; &dsdb; &put; refactor -z; resub; "),
    MacroAction(279, "&get -n; &dsdb; &put; refactor -z; resub; balance; "),
    MacroAction(280, "refactor -z; resub; balance; balance; "),
    MacroAction(281, "resub; balance; balance; fraig; "),
    MacroAction(282, "balance; balance; fraig; &get -n; &sopb; &put; "),
    MacroAction(283, "balance; fraig; &get -n; &sopb; &put; &get -n; &sopb; &put; "),
    MacroAction(284, "fraig; &get -n; &sopb; &put; &get -n; &sopb; &put; refactor -z; "),
    MacroAction(285, "&get -n; &sopb; &put; &get -n; &sopb; &put; refactor -z; refactor -z; "),
    MacroAction(286, "&get -n; &sopb; &put; refactor -z; refactor -z; refactor -z; "),
    MacroAction(287, "refactor -z; refactor -z; refactor -z; &get -n; &dsdb; &put; "),
    MacroAction(288, "refactor -z; refactor -z; &get -n; &dsdb; &put; resub -z; "),
    MacroAction(289, "refactor -z; &get -n; &dsdb; &put; resub -z; &get -n; &dsdb; &put; "),

]


#"""
EXTENDED_MACRO_SPACE: List[MacroAction] = [
    # resyn
    MacroAction(1,  "balance; rewrite; rewrite -z; balance; "),
    MacroAction(2,  "rewrite; rewrite -z; balance; rewrite -z; "),
    MacroAction(3,  "rewrite -z; balance; rewrite -z; balance; "),

    # resyn2
    MacroAction(4,  "balance; rewrite; refactor; balance; "),
    MacroAction(5,  "rewrite; refactor; balance; rewrite; "),
    MacroAction(6,  "refactor; balance; rewrite; rewrite -z; "),
    MacroAction(7,  "rewrite; rewrite -z; balance; refactor -z; "),
    MacroAction(8,  "rewrite -z; balance; refactor -z; rewrite -z; "),
    MacroAction(9,  "balance; refactor -z; rewrite -z; balance; "),

    # resyn2a
    MacroAction(10, "balance; rewrite; balance; rewrite; "),
    MacroAction(11, "rewrite; balance; rewrite; rewrite -z; "),
    MacroAction(12, "balance; rewrite -z; balance; rewrite -z; "),

    # random
    MacroAction(13, "balance; rewrite; refactor; resub; "),
    MacroAction(14, "rewrite; refactor; resub; balance; "),
    MacroAction(15, "refactor; resub; rewrite; balance; "),
    MacroAction(16, "balance; rewrite -z; refactor; resub; "),
    MacroAction(17, "rewrite -z; refactor; resub; balance; "),
    MacroAction(18, "refactor; resub -z; rewrite; balance; "),
    MacroAction(19, "balance; resub; rewrite; rewrite -z; "),
    MacroAction(20, "rewrite; rewrite -z; refactor; resub; "),
    MacroAction(21, "rewrite -z; refactor -z; resub; balance; "),
    MacroAction(22, "refactor -z; resub; rewrite; balance; "),

    MacroAction(23, "balance; fraig; rewrite; refactor; "),
    MacroAction(24, "fraig; rewrite; refactor; resub; "),
    MacroAction(25, "rewrite; fraig; resub; balance; "),
    MacroAction(26, "balance; resub; fraig; rewrite; "),
    MacroAction(27, "fraig; rewrite -z; refactor; balance; "),

    MacroAction(28, "balance; &get -n; &sopb; &put; rewrite; "),
    MacroAction(29, "rewrite; &get -n; &sopb; &put; refactor; "),
    MacroAction(30, "balance; &get -n; &blut; &put; rewrite; "),
    MacroAction(31, "rewrite; &get -n; &blut; &put; refactor; "),
    MacroAction(32, "balance; &get -n; &dsdb; &put; rewrite; "),
    MacroAction(33, "rewrite; &get -n; &dsdb; &put; refactor; "),

    MacroAction(34, "fraig; &get -n; &sopb; &put; balance; "),
    MacroAction(35, "fraig; &get -n; &blut; &put; balance; "),
    MacroAction(36, "fraig; &get -n; &dsdb; &put; balance; "),

    MacroAction(37, "rewrite -z; &get -n; &sopb; &put; balance; "),
    MacroAction(38, "refactor -z; &get -n; &blut; &put; balance; "),
    MacroAction(39, "resub -z; &get -n; &dsdb; &put; balance; "),

    MacroAction(40, "balance; rewrite; &get -n; &sopb; &put; "),

    MacroAction(41, "&get -n; &sopb; &put; &get -n; &blut; &put; refactor; resub -z; "),
    MacroAction(42, "&get -n; &blut; &put; refactor; resub -z; &get -n; &blut; &put; "),
    MacroAction(43, "refactor; resub -z; &get -n; &blut; &put; &get -n; &blut; &put; "),
    MacroAction(44, "resub -z; &get -n; &blut; &put; &get -n; &blut; &put; balance; "),
    MacroAction(45, "&get -n; &blut; &put; &get -n; &blut; &put; balance; &get -n; &dsdb; &put; "),
    MacroAction(46, "&get -n; &blut; &put; balance; &get -n; &dsdb; &put; refactor; "),
    MacroAction(47, "balance; &get -n; &dsdb; &put; refactor; balance; "),
    MacroAction(48, "&get -n; &dsdb; &put; refactor; balance; &get -n; &dsdb; &put; "),
    MacroAction(49, "refactor; balance; &get -n; &dsdb; &put; fraig; "),
    MacroAction(50, "balance; &get -n; &dsdb; &put; fraig; resub; "),
    MacroAction(51, "&get -n; &dsdb; &put; fraig; resub; &get -n; &sopb; &put; "),
    MacroAction(52, "fraig; resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; "),
    MacroAction(53, "resub; &get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; "),
    MacroAction(54, "&get -n; &sopb; &put; &get -n; &dsdb; &put; rewrite -z; fraig; "),
    MacroAction(55, "&get -n; &dsdb; &put; rewrite -z; fraig; balance; "),
    MacroAction(56, "rewrite -z; fraig; balance; resub; "),
    MacroAction(57, "fraig; balance; resub; rewrite; "),
]
#"""

STRUCT_MACRO_SPACE: List[MacroAction] = [
#    MacroAction(1, "rewrite; &get -n; &blut; &put; refactor; &get -n;  &blut; &put; &get -n; &sopb; &put; &get -n; &blut; &put; resub -z; balance; resub -z; resub; refactor -z; &get -n; &dsdb; &put; &get -n; &blut; &put; refactor -z; refactor -z; &get -n; &dsdb; &put; rewrite; rewrite -z; resub -z; resub; "),
    
    MacroAction(1,  "rewrite; &get -n; &blut; &put; refactor; &get -n; &blut; &put; "),
    MacroAction(2,  "&get -n; &blut; &put; rewrite; balance; fraig; "),
    MacroAction(3,  "&get -n; &blut; &put; refactor; rewrite; fraig; "),

    MacroAction(4,  "&get -n; &sopb; &put; fraig; balance; rewrite; "),
    MacroAction(5,  "&get -n; &sopb; &put; rewrite; balance; fraig; "),
    MacroAction(6,  "&get -n; &sopb; &put; refactor; rewrite; fraig; "),

    MacroAction(7,  "&get -n; &dsdb; &put; fraig; balance; rewrite; "),
    MacroAction(8,  "&get -n; &dsdb; &put; rewrite; balance; fraig; "),
    MacroAction(9,  "&get -n; &dsdb; &put; refactor; rewrite; fraig; "),

    MacroAction(10, "&get -n; &blut; &put; fraig; refactor; balance; "),
    MacroAction(11, "&get -n; &sopb; &put; fraig; refactor; balance; "),
    MacroAction(12, "&get -n; &dsdb; &put; fraig; refactor; balance; "),
]

MIX_MACRO_SPACE: List[MacroAction] = [
    MacroAction(13, "fraig; &get -n; &blut; &put; balance; rewrite; "),
    MacroAction(14, "rewrite; &get -n; &sopb; &put; balance; fraig; "),
    MacroAction(15, "fraig; &get -n; &dsdb; &put; rewrite; balance; "),

    MacroAction(16, "balance; rewrite; fraig; rewrite; "),
    MacroAction(17, "rewrite; balance; rewrite; fraig; "),
    MacroAction(18, "fraig; rewrite; balance; fraig; "),

    MacroAction(19, "refactor; rewrite; balance; fraig; "),
    MacroAction(20, "rewrite; refactor; balance; fraig; "),

    MacroAction(21, "balance; fraig; rewrite; balance; "),
    MacroAction(22, "fraig; balance; rewrite; fraig; "),

    MacroAction(23, "&get -n; &blut; &put; balance; rewrite; fraig; "),
    MacroAction(24, "&get -n; &sopb; &put; balance; rewrite; fraig; "),
    MacroAction(25, "&get -n; &dsdb; &put; balance; rewrite; fraig; "),
    MacroAction(26, "rewrite; balance; fraig; balance; "),
]

POLISH_MACRO_SPACE: List[MacroAction] = [
    MacroAction(27, "fraig; balance; fraig; balance; "),
    MacroAction(28, "rewrite; rewrite; balance; fraig; "),
    MacroAction(29, "refactor; balance; rewrite; fraig; "),

    MacroAction(30, "balance; rewrite; balance; rewrite; "),
    MacroAction(31, "fraig; rewrite; fraig; rewrite; "),

    MacroAction(32, "balance; balance; rewrite; fraig; "),
    MacroAction(33, "rewrite; balance; rewrite; balance; "),

    MacroAction(34, "fraig; refactor; balance; fraig; "),
    MacroAction(35, "rewrite; refactor; rewrite; balance; "),

    MacroAction(36, "balance; fraig; balance; fraig; "),

    MacroAction(37, "rewrite; rewrite; rewrite; fraig; "),
    MacroAction(38, "balance; balance; balance; fraig; "),

    MacroAction(39, "fraig; rewrite; balance; rewrite; "),
    MacroAction(40, "refactor; rewrite; balance; fraig; "),
]

TEST_MACRO_SPACE = {
    "struct": STRUCT_MACRO_SPACE,
    "mix": MIX_MACRO_SPACE,
    "polish": POLISH_MACRO_SPACE,
    }
